# Perceptron Implementation in Python

In [1]:
import numpy as np

In [2]:
def sigmoid(x):
    return 1/(1*np.exp(-x))

In [3]:
def sigmoid_derivative(x):
    return x*(1-x)

In [4]:
training_inputs = np.array([[0.25,0.353],
                            [0.25,0.471],
                            [0.5,0.353],
                            [0.5,0.647],
                            [0.75,0.705],
                            [0.75,0.882],
                            [1,0.705],
                            [1,1]])
training_inputs

array([[0.25 , 0.353],
       [0.25 , 0.471],
       [0.5  , 0.353],
       [0.5  , 0.647],
       [0.75 , 0.705],
       [0.75 , 0.882],
       [1.   , 0.705],
       [1.   , 1.   ]])

In [5]:
training_outputs = np.array([[0,1,0,1,0,1,0,1]]).T
training_outputs

array([[0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1]])

In [6]:
np.random.seed(1)

In [7]:
synaptic_weights = 2*np.random.random((2,1))-1

In [8]:
print("Random starting synaptic weights: ")
print(synaptic_weights)

Random starting synaptic weights: 
[[-0.16595599]
 [ 0.44064899]]


In [9]:
for iteration in range(1):
    input_layer = training_inputs
    outputs = sigmoid(np.dot(input_layer, synaptic_weights))

In [10]:
error = training_outputs - outputs
error

array([[-1.12081948],
       [-0.18064001],
       [-1.07526925],
       [-0.2239972 ],
       [-1.20465178],
       [-0.30236965],
       [-1.1556946 ],
       [-0.31612656]])

In [11]:
adjustments = error*sigmoid_derivative(outputs)
synaptic_weights += np.dot(input_layer.T, adjustments)

In [12]:
print("Synaptic weights after training: ")
print(synaptic_weights)

Synaptic weights after training: 
[[0.60736379]
 [1.1753586 ]]


In [13]:
print("Outputs after training: ")
print(outputs)

Outputs after training: 
[[1.12081948]
 [1.18064001]
 [1.07526925]
 [1.2239972 ]
 [1.20465178]
 [1.30236965]
 [1.1556946 ]
 [1.31612656]]
